name: Terraform
author: Sean Christians
description: Manage deployments with Terraform

inputs:
  sops-age-key:
    description: Encryption key for SOPS secrets stored in Terraform stacks.
  stack:
    description: Path to Terraform code.
    required: true

runs:
  using: composite
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

    - name: Select Terraform provisioning stage
      id: mode
      shell: bash
      env:
        MODE: ${{ github.ref_name == github.event.repository.default_branch && 'apply' || 'plan' }}
      run: |
        echo "mode=$MODE" >> $GITHUB_OUTPUT

    - name: Terraform environment
      shell: bash
      env:
        STACK: ${{ inputs.stack }}
      run: |
        echo "TF_IN_AUTOMATION=true" >> $GITHUB_ENV
        echo "STACK=$STACK" >> $GITHUB_ENV

    - name: Terraform backend
      shell: bash
      working-directory: ${{ inputs.stack }}
      run: |
        cat > backend.tf << HCP
        terraform {
          backend "s3" {
            bucket       = "seanchristians-lab-terraform-state"
            key          = "$STACK/terraform.tfstate"
            region       = "ca-central-1"
            use_lockfile = true
          }
        }
        HCP

    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
      with:
        aws-region: ca-central-1
        role-to-assume: arn:aws:iam::352505431850:role/GitHubActionsTerraformRole

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.stack }}
      run: |
        terraform init

    - name: Terraform Validate
      if: steps.mode.outputs.mode == 'plan'
      shell: bash
      working-directory: ${{ inputs.stack }}
      run: |
        terraform validate

    - name: Terraform Plan
      if: steps.mode.outputs.mode == 'plan'
      shell: bash
      working-directory: ${{ inputs.stack }}
      env:
        SOPS_AGE_KEY: ${{ inputs.sops-age-key }}
      run: |
        terraform plan -input=false -no-color -compact-warnings >> $GITHUB_STEP_SUMMARY

    - name: Terraform Apply
      if: steps.mode.outputs.mode == 'apply'
      shell: bash
      working-directory: ${{ inputs.stack }}
      env:
        SOPS_AGE_KEY: ${{ inputs.sops-age-key }}
      run: |
        terraform apply -input=false -auto-approve
