name: minecraft

services:
  game:
    image: docker.io/itzg/minecraft-server@sha256:1e6af837a25532c8567cd4130d1609391fdc472e9e37aecab9eac0d6f4ed7593 # 2026.6.0-java25-alpine
    tty: true
    stdin_open: true
    restart: unless-stopped
    stop_grace_period: 3m

    ports:
      - "25565:25565/tcp"
      - "19132:19132/udp"

    volumes:
      - type: bind
        source: /home/core/minecraft
        target: /data
        bind:
          selinux: Z

    environment:
      VERSION: 26.1.2
      TYPE: FABRIC
      EULA: "true"
      MEMORY: 10G
      STOP_SERVER_ANNOUNCE_DELAY: 120
      ENABLE_WHITELIST: true
      ENABLE_QUERY: true
      MODRINTH_PROJECTS: "@/data/modrinth.lock.txt"
      VANILLATWEAKS_SHARECODE: UEHYo3,8APkq2
      DIFFICULTY: normal
      SPAWN_PROTECTION: 0
      ENABLE_COMMAND_BLOCK: true
      BROADCAST_CONSOLE_TO_OPS: true
      BROADCAST_RCON_TO_OPS: true
