version: 2
updates:
  - package-ecosystem: terraform
    directories:
      - infrastructure/**
    schedule:
      interval: monthly
    cooldown:
      default-days: 5

  - package-ecosystem: github-actions
    directories:
      - /
      - /actions/*
    schedule:
      interval: monthly
    cooldown:
      default-days: 5
