name: Tailscale Login
author: Sean Christians
description: Authenticate to Tailscale with workload identity federation

inputs:
  client-id:
    description: Your Tailscale OIDC Federated Identity Client ID
    required: true
  audience:
    description: Your Tailscale OIDC Federated Identity Audience
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      env:
        CLIENT_ID: ${{ inputs.client-id }}
        AUDIENCE: ${{ inputs.audience }}
      run: |
        ACCESS_TOKEN=$(
          curl -sSL --retry 5 --retry-all-errors -G \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          --data-urlencode "audience=$AUDIENCE" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value'
        )

        echo "TAILSCALE_OAUTH_CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
        echo "TAILSCALE_IDENTITY_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
