name: Tailscale Login
author: Sean Christians
description: Authenticate to Tailscale with workload identity federation

inputs:
  client-id:
    description: Your Tailscale OIDC Federated Identity Client ID
    required: true
  audience:
    description: Your Tailscale OIDC Federated Identity Audience
    required: true

runs:
  using: composite
  steps:
    - name: Request GitHub OIDC Token
      shell: bash
      run: |
        TOKEN=$(
          curl -sL \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          --data-urlencode 'audience=${{ inputs.audience }}' \
          "$ACTIONS_ID_TOKEN_REQUEST_URL"
        )

        echo "${TOKEN}"

        echo "TAILSCALE_IDENTITY_TOKEN=${TOKEN}" >> $GITHUB_ENV
        echo 'TAILSCALE_OAUTH_CLIENT_ID=${{ inputs.client-id }}' >> $GITHUB_ENV
