name: Tailscale Login
author: Sean Christians
description: Authenticate to Tailscale with workload identity federation

inputs:
  client-id:
    description: Your Tailscale OIDC Federated Identity Client ID
    required: true
  audience:
    description: Your Tailscale OIDC Federated Identity Audience
    required: true

runs:
  using: composite
  steps:
    - name: Request GitHub OIDC Token
      id: oidc-token
      uses: seanchristians/lab/actions/github-actions-oidc@main
      with:
        audience: ${{ inputs.audience }}

    - shell: bash
      env:
        OIDC_TOKEN: ${{ steps.oidc-token.outputs.oidc-token }}
        CLIENT_ID: ${{ inputs.client-id }}
      run: |
        echo "TAILSCALE_IDENTITY_TOKEN=$OIDC_TOKEN" >> $GITHUB_ENV
        echo "TAILSCALE_OAUTH_CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
