name: GitHub Actions OIDC Token
author: Sean Christians
description: Request an OpenID Connect token from GitHub Actions

inputs:
  audience:
    description: OpenID Service Provider Expected Audience
    required: true

outputs:
  oidc-token:
    description: OpenID Connect Token
    value: ${{ steps.request-token.outputs.oidc-token }}

runs:
  using: composite
  steps:
    - shell: bash
      id: request-token
      run: |
        export TOKEN=$(
          curl -sL -G \
          -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          --data-urlencode 'audience=${{ inputs.audience }}' \
          "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value'
        )

        echo "oidc-token=${TOKEN}" >> $GITHUB_OUTPUT
