name: terraform init
description: This action initializes terraform with the AWS S3 backend

inputs:
  aws-role-arn:
    description: "AWS IAM role ARN for Terraform, both for the AWS provider and for the S3 state backend."
    required: true

runs:
  using: composite
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Setup Environment
      shell: bash
      run: |
        echo '${{ secrets.GITHUB_TOKEN }}' > github_token.txt
        echo 'AWS_WEB_IDENTITY_TOKEN_FILE=github_token.txt' >> $GITHUB_ENV
        echo 'AWS_ROLE_ARN=${{ inputs.aws-role-arn }}' >> $GITHUB_ENV

    - name: terraform init
      shell: bash
      run: terraform init -input=false
