name: terraform init
description: This action initializes terraform with the AWS S3 backend.

inputs:
  aws-role-arn:
    description: AWS IAM role ARN for Terraform, both for the AWS provider and for the S3 state backend.
    required: true

runs:
  using: composite
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: ca-central-1
        role-to-assume: ${{ inputs.aws-role-arn }}

    - uses: actions/checkout@v5

    - name: terraform init
      shell: bash
      run: terraform init -input=false
