name: Terraform
author: Sean Christians
description: Manage deployments with Terraform

inputs:
  sops-age-key:
    description: Encryption key for SOPS secrets stored in Terraform stacks.
  stack:
    description: Path to Terraform code.
    required: true
  mode:
    description: Terraform provisioning step.

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

    - name: Terraform environment
      shell: bash
      run: |
        echo "TF_IN_AUTOMATION=true" >> $GITHUB_ENV

    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
      with:
        aws-region: ca-central-1
        role-to-assume: arn:aws:iam::352505431850:role/GitHubActionsTerraformRole

    - name: Import stack context action
      if: ${{ hashFiles(format('{0}/action.yaml', inputs.stack)) != '' }}
      shell: bash
      env:
        STACK: ${{ inputs.stack }}
      run: |
        mkdir "$GITHUB_WORKSPACE/context"
        cp "$STACK/action.yaml" "$GITHUB_WORKSPACE/context/"

    - name: Run stack context action
      if: ${{ hashFiles(format('{0}/action.yaml', inputs.stack)) != '' }}
      uses: ./context
      with:
        mode: ${{ inputs.mode }}

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.stack }}
      env:
        STACK: ${{ inputs.stack }}
      run: |
        cat > backend.tf << HCP
        terraform {
          backend "s3" {
            bucket       = "seanchristians-lab-terraform-state"
            key          = "$STACK/terraform.tfstate"
            region       = "ca-central-1"
            use_lockfile = true
          }
        }
        HCP

        terraform init

    - name: Terraform Validate
      if: inputs.mode != 'apply'
      shell: bash
      working-directory: ${{ inputs.stack }}
      run: |
        terraform validate

    - name: Terraform Plan
      if: inputs.mode == 'plan'
      shell: bash
      working-directory: ${{ inputs.stack }}
      env:
        SOPS_AGE_KEY: ${{ inputs.sops-age-key }}
      run: |
        terraform plan -input=false -no-color -compact-warnings >> $GITHUB_STEP_SUMMARY

    - name: Terraform Apply
      if: inputs.mode == 'apply'
      shell: bash
      working-directory: ${{ inputs.stack }}
      env:
        SOPS_AGE_KEY: ${{ inputs.sops-age-key }}
      run: |
        terraform apply -input=false -auto-approve
