name: Authenticate Terraform Providers
author: Sean Christians
description: Authenticate with Terraform providers by setting their environment variables.

inputs:
  step:
    description: Terraform step, either plan or apply
    default: plan
  stack:
    description: Path to Terraform code
    required: true

runs:
  using: composite
  steps:
    - name: Download SOPS
      shell: bash
      run: |
        gh release download -R getsops/sops -p 'sops-*.linux.amd64' -O '/usr/local/bin/sops'
        chmod +x '/usr/local/bin/sops'

    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-region: ca-central-1
        role-to-assume: arn:aws:iam::352505431850:role/GitHubActionsTerraformRole

    - name: Authenticate with Tailscale
      if: inputs.stack == 'infrastructure/network'
      uses: seanchristians/lab/actions/tailscale-login@main
      with:
        client-id: TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
        audience: api.tailscale.com/TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL

    - name: Join Tailnet
      if: inputs.stack == 'infrastructure/acme' && inputs.step == 'apply'
      uses: tailscale/github-action@v4
      with:
        oauth-client-id: TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
        audience: api.tailscale.com/TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
        tags: tag:ci
        version: latest
        ping: veronica.scchq.net
