name: Terraform init
author: Sean Christians
description: Initialize Terraform

inputs:
  working-directory:
    description: Path to Terraform working directory. Defaults to the current working directory (.)
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      shell: bash
      env:
        TF_IN_AUTOMATION: true
        WORKDIR: ${{ inputs.working-directory }}
      run: |
        terraform -chdir="$WORKDIR" init
