name: Terraform Module Network
on:
  pull_request:
    paths:
      - infrastructure/network/**
  push:
    branches:
      - main
    paths:
      - infrastructure/network/**
      - ansible-playbooks/*
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

env:
  PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
  PORKBUN_SECRET_API_KEY: ${{ secrets.PORKBUN_SECRET_API_KEY }}
  DESEC_API_TOKEN: ${{ secrets.DESEC_API_TOKEN }}

jobs:
  terraform:
    name: ${{ github.ref_name == github.event.repository.default_branch && 'apply' || 'plan' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Authenticate with Tailscale API
        env:
          CLIENT_ID: ${{ vars.TAILSCALE_CLIENT_ID }}
          AUDIENCE: ${{ format('api.tailscale.com/{0}', vars.TAILSCALE_CLIENT_ID) }}
        run: |
          ACCESS_TOKEN=$(
            curl -sSL --retry 5 --retry-all-errors -G \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            --data-urlencode "audience=$AUDIENCE" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value'
          )

          echo "TAILSCALE_OAUTH_CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
          echo "TAILSCALE_IDENTITY_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Connect to Tailnet
        uses: tailscale/github-action@306e68a486fd2350f2bfc3b19fcd143891a4a2d8 # v4.1.2
        with:
          oauth-client-id: ${{ vars.TAILSCALE_CLIENT_ID }}
          audience: ${{ format('api.tailscale.com/{0}', vars.TAILSCALE_CLIENT_ID) }}
          tags: tag:ci
          version: 1.98.2

      - name: Install Ansible collections
        working-directory: infrastructure/network
        run: ansible-galaxy collection install cloud.terraform

      - name: Cache Ansible collections
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.ansible/collections
          key: ${{ runner.os }}-ansible-collections-${{ hashFiles('~/.ansible/collections/**/*') }}
          restore-keys: |
            ${{ runner.os }}-ansible-collections-

      - name: Terraform
        uses: seanchristians/lab/actions/terraform@main
        with:
          module: infrastructure/network
          tf_backend_s3_bucket: ${{ vars.TF_BACKEND_AWS_BUCKET }}
          aws_region: ${{ vars.TF_BACKEND_AWS_REGION }}
          aws_role: ${{ vars.TF_BACKEND_AWS_ROLE }}
          terraform_version: "v1.16.0-alpha20260513" # Required for 'store' blocks in terraform_data resources

      - name: Run Ansible Playbooks
        working-directory: infrastructure/network
        env:
          CHECK_MODE: ${{ github.ref_name == github.event.repository.default_branch && '--check' || '' }}
        run: |
          ansible-playbook "$CHECK_MODE" ansible-playbooks/*.yaml
