name: Network stack context
author: Sean Christians
description: Provide context and automation for the Network stack.

inputs:
  mode:
    description: Terraform provisioning step
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate with Tailscale
      uses: seanchristians/lab/actions/tailscale-login@main
      with:
        client-id: TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
        audience: api.tailscale.com/TA1163u8TV11CNTRL-kTzGLf2dGf11CNTRL
