---
- name: Configure dynamic DNS with deSEC.io
  hosts: ddns
  tasks:
    - name: Create folder for ddns scripts
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/ddns"
        state: directory

    - name: Create folder for systemd units
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/systemd/user"
        state: directory

    - name: Install ddns.sh
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/ddns/ddns.sh"
        mode: 0500
        content: |
          #!/bin/bash -e

          TAILSCALE_DATA=$(/usr/sbin/mktemp)

          /usr/sbin/tailscale netcheck --format json 2>/dev/null > "$TAILSCALE_DATA"

          DEVICE_IPV4=$(/usr/sbin/jq -r '.GlobalV4' "$TAILSCALE_DATA" | /usr/sbin/sed 's/:[[:digit:]]\+$//g')
          DEVICE_IPV6=$(/usr/sbin/jq -r '.GlobalV6' "$TAILSCALE_DATA" | /usr/sbin/sed 's/:[[:digit:]]\+$//g' | /usr/sbin/tr -d '[]')

          /usr/sbin/curl -G -sSL --fail --retry 5 --retry-all-errors \
          -H "Authorization: Token {{ desec_token }}" \
          --data-urlencode "hostname={{ subdomain }}.{{ desec_domain }}" \
          --data-urlencode "myipv4=$DEVICE_IPV4" \
          --data-urlencode "myipv6=$DEVICE_IPV6" \
          "https://update.dedyn.io"

          /usr/sbin/rm "$TAILSCALE_DATA"

    - name: Systemd service to update DNS
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config/systemd/user/ddns.service"
        content: |
          [Unit]
          Description=Update DNS record for this server
          Wants=network-online.target
          After=network-online.target

          [Service]
          Type=oneshot
          ExecStart={{ ansible_env.HOME }}/ddns/ddns.sh

          [Install]
          WantedBy=multi-user.target

    - name: Systemd timer to run ddns.service
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config/systemd/user/ddns.timer"
        content: |
          [Unit]
          Description=Updates DNS every hour

          [Timer]
          OnUnitActiveSec=1h
          Persistent=true
          Unit=ddns.service

          [Install]
          WantedBy=timers.target

    - name: Enable systemd services
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: ddns.timer
        state: restarted
        scope: user

    - name: Quickstart DDNS update
      ansible.builtin.systemd_service:
        name: ddns.service
        state: started
        scope: user
