---
- name: Set up a Minecraft server
  hosts: minecraft_servers
  tasks:
    - name: Create Minecraft data volume
      ansible.builtin.file:
        path: ~/minecraft
        state: directory

    - name: Podman network
      containers.podman.podman_network:
        name: minecraft
        state: quadlet
        quadlet_options:
          - IPv6=true
        opt:
          isolate: true

    - name: Minecraft container
      containers.podman.podman_container:
        name: minecraft
        image: docker.io/itzg/minecraft-server:latest
        volume: ~/minecraft:/data:Z
        state: quadlet
        network: minecraft.network
        quadlet_options:
          - |
            [Install]
            WantedBy=default.target
        env:
          VERSION: 26.1.2
          EULA: "true"
          TYPE: FABRIC
          MODRINTH_PROJECTS: fabric-api,floodgate,lithium,ferrite-core
          MODS: https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/fabric
          MEMORY: 10G
          DIFFICULTY: normal
          ENABLE_COMMAND_BLOCK: true
      notify: Start Minecraft container

  handlers:
    - name: Start Minecraft container
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: minecraft
        state: restarted
      become: yes
