---
- name: Set up a Minecraft server
  hosts: minecraft_servers
  tasks:
    - name: Create Minecraft data volume
      become_method: containers.podman.podman_unshare
      become: true
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/minecraft"
        state: directory
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"

    - name: Install Modrinth projects lock-file
      become_method: containers.podman.podman_unshare
      become: true
      ansible.builtin.copy:
        src: ../services/minecraft-server/modrinth.lock.txt
        dest: "{{ ansible_env.HOME }}/minecraft/modrinth.lock.txt"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0444

    - name: Install Minecraft service Quadlets
      ansible.builtin.copy:
        src: ../services/minecraft-server/systemd
        dest: "{{ ansible_env.HOME }}/.config/containers/systemd"
      notify: Start Minecraft container

    - name: Open Minecraft Java server port
      become: true
      ansible.posix.firewalld:
        port: 25565/tcp
        permanent: true
        state: enabled

    - name: Open Minecraft Bedrock server port
      become: true
      ansible.posix.firewalld:
        port: 19132/udp
        permanent: true
        state: enabled

  handlers:
    - name: Start Minecraft container
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user
        name: minecraft-game
        enabled: true
        state: restarted
