---
- name: Configure wg-easy with Podman
  hosts: wireguard_servers
  tasks:
    - name: load wireguard kernel module
      community.general.modprobe:
        name: wireguard
        persistent: present

    - name: load nftables kernel module
      community.general.modprobe:
        name: nft_masq
        persistent: present

    - name: load iptable_nat kernel module
      community.general.modprobe:
        name: iptable_nat
        persistent: present

    - name: local ip6table_nat kernel module
      community.general.modprobe:
        name: ip6table_nat
        persistent: present

    - name: Create systemd unit folder
      ansible.builtin.file:
        path: /etc/containers/systemd/wg-easy
        state: directory

    - name: Create container volume folder
      ansible.builtin.file:
        path: /etc/containers/volumes/wg-easy
        state: directory

    - name: Tailscale podman network
      containers.podman.podman_network:
        name: tailscale
        quadlet_options:
          - IPv6=true
        state: quadlet

    - name: Tailscale pod
      containers.podman.podman_pod:
        name: tailscale
        network: tailscale.network
        publish:
          - 51820:51820/udp
        quadlet_options:
          - |
            [Install]
            WantedBy=default.target
        state: quadlet

    - name: Tailscale Podman container
      containers.podman.podman_container:
        name: tailscale
        image: docker.io/tailscale/tailscale:v1.98.3
        env:
          TS_AUTHKEY: "{{ tailscale_auth_key }}"
        cap_add:
          - NET_ADMIN
          - NET_RAW
        pod: tailscale.pod
        quadlet_options:
          - "AutoUpdate=registry"
          - |
            [Install]
            WantedBy=default.target
        state: quadlet

    - name: wg-easy Podman container
      containers.podman.podman_container:
        name: wg-easy
        image: ghcr.io/wg-easy/wg-easy:15
        volume: /etc/containers/volumes/wg-easy:/etc/wireguard:Z
        env:
          INSECURE: true
          INIT_ENABLED: "true"
          INIT_USERNAME: admin
          INIT_PASSWORD: "Password-1234"
          INIT_HOST: "{{ wireguard_domain }}"
          INIT_PORT: 51820
          INIT_DNS: "{{ wireguard_dns }}"
          INIT_IPV4_CIDR: "{{ wireguard_ipv4_cidr }}"
          INIT_IPV6_CIDR: "{{ wireguard_ipv6_cidr }}"
          INIT_ALLOWED_IPS: "{{ wireguard_ipv4_cidr }},{{ wireguard_ipv6_cidr }}"
        cap_add:
          - NET_ADMIN
          - SYS_MODULE
          - NET_RAW
        sysctl:
          net.ipv4.ip_forward: 1
          net.ipv4.conf.all.src_valid_mark: 1
          net.ipv6.conf.all.disable_ipv6: 0
          net.ipv6.conf.all.forwarding: 1
          net.ipv6.conf.default.forwarding: 1
        pod: tailscale.pod
        quadlet_dir: /etc/containers/systemd/wg-easy
        quadlet_options:
          - "AutoUpdate=registry"
          - |
            [Install]
            WantedBy=default.target
        state: quadlet

    - name: service to serve wg-easy admin page to tailnet
      ansible.builtin.copy:
        dest: /etc/systemd/system/serve-wg-easy.service
        content: |
          [Unit]
          Description=Serve the wg-easy admin port in the Tailnet
          After=tailscale.service
          Requires=tailscale.service

          [Service]
          Type=oneshot
          ExecStart=podman container exec tailscale tailscale serve --service={{ tailnet_service }} 51821

          [Install]
          WantedBy=multi-user.target

    - name: start tailscale container
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: tailscale
        state: started

    - name: start wg-easy with systemd
      ansible.builtin.systemd_service:
        name: wg-easy
        state: restarted

    - name: serve wg-easy to tailnet
      ansible.builtin.systemd_service:
        name: serve-wg-easy
        state: started
