---
- name: Configure wg-easy with Podman
  hosts: wireguard_servers
  remote_user: root
  tasks:
    - name: load wireguard kernel module
      community.general.modprobe:
        name: wireguard
        persistent: present

    - name: load nftables kernel module
      community.general.modprobe:
        name: nft_masq
        persistent: present

    - name: load iptable_nat kernel module
      community.general.modprobe:
        name: iptable_nat
        persistent: present

    - name: local ip6table_nat kernel module
      community.general.modprobe:
        name: ip6table_nat
        persistent: present

    - name: Create systemd unit folder
      ansible.builtin.file:
        path: /etc/containers/systemd/wg-easy
        state: directory

    - name: Create container volume folder
      ansible.builtin.file:
        path: /etc/containers/volumes/wg-easy
        state: directory

    - name: Tailscale podman network
      containers.podman.podman_network:
        name: tailscale
        quadlet_options:
          - IPv6=true
        state: quadlet

    - name: Tailscale container
      containers.podman.podman_container:
        name: tailscale
        image: tailscale/tailscale:1.98.3
        env:
          TS_AUTHKEY: "{{ tailscale_auth_key }}"
        cap_add:
          - NET_ADMIN
          - NET_RAW
        network:
          - tailscale.network
        quadlet_options:
          - "AutoUpdate=registry"
          - |
            [Install]
            WantedBy=default.target
        state: quadlet

    - name: wg-easy podman container
      containers.podman.podman_container:
        name: wg-easy
        image: ghcr.io/wg-easy/wg-easy:15
        volume: /etc/containers/volumes/wg-easy:/etc/wireguard:Z
        publish:
          - 51820:51820/udp
        env:
          INSECURE: true
          INIT_ENABLED: "true"
          INIT_USERNAME: admin
          INIT_PASSWORD: "Password-1234"
          INIT_HOST: vpn.seanchristians.ca
          INIT_PORT: 51820
          INIT_DNS: 149.112.121.10,149.112.122.10,2620:10A:80BB::10,2620:10A:80BC::10 # CIRA Canadian Shield
          INIT_IPV4_CIDR: 172.30.0.0/24
          INIT_IPV6_CIDR: fdef:aced::/64
          INIT_ALLOWED_IPS: 172.30.0.0/24,fdef:aced::/64
        cap_add:
          - NET_ADMIN
          - SYS_MODULE
          - NET_RAW
        sysctl:
          net.ipv4.ip_forward: 1
          net.ipv4.conf.all.src_valid_mark: 1
          net.ipv6.conf.all.disable_ipv6: 0
          net.ipv6.conf.all.forwarding: 1
          net.ipv6.conf.default.forwarding: 1
        network:
          - tailscale.network
        quadlet_dir: /etc/containers/systemd/wg-easy
        quadlet_options:
          - "AutoUpdate=registry"
          - |
            [Install]
            WantedBy=default.target
        state: quadlet

    - name: start tailscale container
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: tailscale
        state: started

    - name: start wg-easy with systemd
      ansible.builtin.systemd_service:
        name: wg-easy
        state: restarted

    - name: Publish wg-easy admin portal with Tailscale HTTPS
      containers.podman.podman_container_exec:
        name: tailscale
        command: tailscale serve --service svc:wg-easy 51821
